
["Blue Skies Extra Settings"]
	#Range: > 6
	"gate keeper house spacing" = 18
	"enable blue skies nerf" = true
	"allow every mod generate features in blue skies dimensions" = false

["Headshot Extra Settings"]
	"enable 'Ding' on Headshot" = true
	#Range: 0.0F ~ 1.0F. Type: Float
	"'Ding' volume" = 1.0
	#Range: 0.5F ~ 2.0F. Type: Float
	"'Ding' pitch" = 1.0

["Cracker's Wither Storm Mod Optimization Settings"]
	"don't let the wither sickness ticking system affect monsters, NOT AVAILABLE YET" = false
	"don't let the wither sickness ticking system affect animals, NOT AVAILABLE YET" = false
	#Every settings here will improve performance a lot as the mod is really laggy
	"let wither sickness ticking system only take effect on players, NOT AVAILABLE YET" = false
	#Entities that will be killed: Block Cluster, Sickened Skeleton, Sickened Creeper, Sickened Spider, Sickened Zombie, Tentacle, Withered Symbiont.
	#Inspired by Lag Removal mod.
	"kill witherstormmod entities after command block dies" = false
	"reduce the wither storm chunks activity by one half, NOT AVAILABLE YET" = false
	#With this turning on, the amount of block clusters will be reduced on rendering and they won't be rendered when no player see them, NOT AVAILABLE YET
	"block cluster render optimization" = false

["L_Ender's Cataclysm Extra Settings"]
	#Range: > 5
	"burning arena spacing" = 112
	#Range: > 5
	"ruined citadel separation" = 10
	#Range: > 5
	"ruined citadel spacing" = 30
	#Range: > 5
	"soul black smith separation" = 70
	#Range: > 5
	"burning arena separation" = 70
	#Range: > 5
	"soul black smith spacing" = 90

["The Undergarden Extra Settings"]
	#Range: > 5
	"catacomb spacing" = 24
	#Range: > 5
	"catacomb separation" = 8

#Opotato Common Config
["Opotato Settings"]
	#Range: 1 ~ 100
	"max entities spawning number per chunk" = 10
	"allow entities spawn limit" = false
	"enable creative one pouch" = true
	"print mods list when launching game" = true
	"entities whose spawn won't be limited" = ["modid:mobid"]

["Ars Nouveau Extra Settings"]
	"disable mana gems generation in basic loot chests" = false

